### ISSUE TITLE
Fail to compile example with Arm Compiler

### ISSUE THREAD

**Issue by MarceloSalazar** [ARMmbed/mbed-os-example-s1sbp6a#4]
I've tried to import in Mbed Studio and attempted to compile.

I'm seeing this compile issue:
```
Compile [  2.9%]: ecg_example.cpp
[Fatal Error] ecg_example.cpp@20,10: 'ecg_api.h' file not found
[ERROR] ./ecg_example.cpp:20:10: fatal error: 'ecg_api.h' file not found
```

Version of components used in this application
```
mbed-os-example-s1sbp6a (#6f642f41c38e)
`- mbed-os (#8ef0a435b235, tags: mbed-os-6.4.0, mbed-os-6.4.0-rc1)
```

Note the example is expected to work out of the box. Patches shouldn't be required.
Proposed fix: add `.lib` files with references to other required libraries (similar to mbed-os.lib)

@ARMmbed/team-samsung please review

**Comment by heuisam** [comment]
Hi @MarceloSalazar 

Did you import afe_lib and mbed_dsp lib?
You have to apply the patch in guide.
https://github.com/ARMmbed/mbed-os-example-s1sbp6a#download-library--apply-patch

**Comment by heuisam** [comment]
Hi @MarceloSalazar

I fix this issue in this PR, https://github.com/ARMmbed/mbed-os-example-s1sbp6a/commit/92d01e40602dfbaec3b5ecfd565651b4d4704697

**Comment by MarceloSalazar** [comment]
I've tested and works great. Thanks!
